<?
$jsonData = '[
{"site" : "*toolbardev.com/3beats/*", "start" : "//body"},
{"site" : "*blog.sports.3beats.com/*", "start" : "//div[contains(@class, \'post-content\')]"},
{"site" : "sports.3beats.com/*", "start" : "//div[contains(@class, \'post-content\')]"},

{"site" : "*espn.go.com*", "start" : "//div[contains(@class, \'article\')]"},
{"site" : "*people.com/people/*", "start" : "//div[@id=\'articlebody\']", "exclude" : ["//p[@class=\'caption\']", "//div(@id=\'peopleTop5\')", "//div(@class=\'startracks\')", "//div(@id=\'hottopicsnav\')"]},
{"site" : "*tmz.com*", "start" : "//div[contains(@class,\'body\')]", "exclude" : ["//div[@class=\'breadcrumbs\']", "//div[@class=\'swipe\']"]},
{"site" : "*zimbio.com*", "start" : "//div[contains(@id=\'zBlog\')]"},
{"site" : "*eonline.com*", "start" : "//div[contains(@class,\'blog_entry\')]"},
{"site" : "*theinsider.com/news/*", "start" : "//div[contains(@id=\'article-main\')]"},
{"site" : "*usmagazine.com*", "start" : "//div[contains(@class, \'article_content\')]"},
{"site" : "*asylum.com*", "start" : "//div[contains(@class, \'articleBody\')]"},
{"site" : "*ew.com*", "start" : "//div[contains(@class, \'storycontent\')]"},
{"site" : "*askmen.com*", "start" : "//div[contains(@id, \'content\')]"},
{"site" : "*perezhilton.com*", "start" : "//div[contains(@class, \'entry\')]"},
{"site" : "*accesshollywood.com*", "start" : "//div[contains(@id, \'module article\')]"},
{"site" : "*dailymail.co.uk*", "start" : "//div[contains(@class, \'article-advert-body\')]"},
{"site" : "*starpulse.com*", "start" : "//div[contains(@class, \'article_content\')]"},
{"site" : "*popsugar.com*", "start" : "//div[contains(@id, \'post-content\')]"},
{"site" : "*etonline.com*", "start" : "//*[@id=\'hub_mid_container\']"},
{"site" : "*thesuperficial.com*", "start" : "//div[contains(@class, \'entry\')]"},
{"site" : "*sports.yahoo.com*", "start" : "//div[contains(@class, \'body_copy\')]"},
{"site" : "*nfl.com*", "start" : "//div[contains(@class, \'entry\')]"},
{"site" : "*msn.foxsports.com*", "start" : "//div[contains(@class, \'fs-article\')]"},
{"site" : "*mlb.com/news*", "start" : "//div[contains(@id, \'article_body\')]"},
{"site" : "*cbssports.com*", "start" : "//div[contains(@class, \'featureComponent\')]"},
{"site" : "*sportingnews.com*", "start" : "//div[contains(@class, \'storyArticle\')]"},
{"site" : "*sportsillustrated.cnn.com*", "start" : "//div[contains(@id, \'cnnStoryContent\')]"},
{"site" : "*nbcsports.msnbc.com*", "start" : "//div[contains(@class, \'textSmall\')]"},
{"site" : "*nba.com*", "start" : "//div[contains(@id, \'nbaGINotebook\')]"},
{"site" : "*thegolfchannel.com*", "start" : "//div[contains(@class, \'article\')]"},
{"site" : "*politicsdaily.com*", "start" : "//div[contains(@class, \'artCotents\')]"},
{"site" : "*economist.com*", "start" : "//div[contains(@class, \'ec-blog-body\')]"},
{"site" : "*politico.com/news*", "start" : "//div[contains(@class, \'story-wrapper\')]"},
{"site" : "*politico.com/blogs*", "start" : "//div[contains(@class, \'post\')]"},
{"site" : "*barackobama.com*", "start" : "//div[contains(@class, \'body\')]"},
{"site" : "*journals.democraticunderground.com*", "start" : "//div[contains(@class, \'jmessage-body\')]"},
{"site" : "*townhall.com/news*", "start" : "//div[contains(@class, \'adspot\')]"},
{"site" : "*voanews.com/english/news*", "start" : "//div[contains(@class, \'boxout article\')]"},
{"site" : "*guardian.co.uk*", "start" : "//div[contains(@id=\'article-body-blocks\')]"},
{"site" : "*newsbusters.org*", "start" : "//div[contains(@id, \'main-content\')]"},
{"site" : "*humanevents.com*", "start" : "//div[contains(@class, \'article_body\')]"},
{"site" : "*newsbusters.org/blogs*", "start" : "//div[contains(@id, \'blog_text\')]"},
{"site" : "*politifact.com*", "start" : "//div[contains(@id, \'content\')]"},
{"site" : "*front.moveon.org*", "start" : "//div[contains(@class, \'entry-content\')]"},
{"site" : "*factcheck.org*", "start" : "//div[contains(@id=\'content\')]"},
{"site" : "*aclu.org*", "start" : "//div[contains(@class, \'serendipity_entry_body\')]"},
{"site" : "*redstate.com*", "start" : "//div[contains(@id=\'entry\')]"},
{"site" : "*touchappmedia.com*", "start" : "//div[contains(@id=\'content\')]"},
{"site" : "*govtrack.us/blog*", "start" : "//div[contains(@class=\'postcontent\')]"},
{"site" : "*techdailydose.nationaljournal.com*", "start" : "//div[contains(@class=\'entrybody\')]"},
{"site" : "*patriotpost.us*", "start" : "//div[contains(@class=\'box content\')]"},
{"site" : "*swamppolitics.com/news*", "start" : "//div[contains(@class=\'story-body\')]"},
{"site" : "*blog.foreignpolicy.com/posts*", "start" : "//div[contains(@class=\'blog_body\')]"},
{"site" : "*motherjones.com*", "start" : "//div[contains(@id, \'content-area,class \'clear-block\')]"},
{"site" : "*campaignforliberty.com*", "start" : "//div[contains(@id=\'content\')]"},
{"site" : "*trust.org/alertnet/blogs*", "start" : "//div[contains(@class=\'article module content\')]"},
{"site" : "*numbersusa.com/content/nusablog*", "start" : "//div[contains(@class=\'content\')]"},
{"site" : "*numbersusa.com/content/news*", "start" : "//div[contains(@id, \'tabset-2\')]"},
{"site" : "*thegrio.com*", "start" : "//div[contains(@class=\'article_body\')]"},
{"site" : "*gopusa.com/news*", "start" : "//div[contains(@class=\'post_content\')]"},
{"site" : "*news.yahoo.com*", "start" : "//div[contains(@class=\'yn-story-content\')]", "exclude" : ["//div[contains(@id=\'yn-story-related-media\')]", "//p(@class=\'ynw-standfirst\')", "//div(@id=\'ynw-image-video-inset\')"]},
{"site" : "*news.blogs.cnn.com*", "start" : "//div[contains(@class=\'cnnBlogContentPost\')]"},
{"site" : "*msnbc.msn.com*", "start" : "//div[contains(@class=\'page i1 txt\')]"},
{"site" : "*aolnews.com*", "start" : "//div[contains(@id, \'article-entry-content\')]"},
{"site" : "*abcnews.go.com*", "start" : "//div[contains(@class=\'story_text\')]"},
{"site" : "*numbersusa.com/content/news*", "start" : "//div[contains(@id, \'article-section\')]"},
{"site" : "*cbsnews.com*", "start" : "//div[contains(@class=\'storyBodyText\')]"},
{"site" : "*examiner.com*", "start" : "//div[contains(@class=\'clearfix entry-content\')]"},
{"site" : "*numbersusa.com/content/news*", "start" : "//div[contains(@id, \'insider_ad_wrapper\')]"},
{"site" : "*bbc.co.uk/news*", "start" : "//div[contains(@id, \'story_continues_1\')]"},
{"site" : "*npr.org*", "start" : "//div[contains(@id, \'storytext\')]"},
{"site" : "*ap.org.com*", "start" : "//span[contains(@class=\'entry-content\')]"},
{"site" : "*usnews.com*", "start" : "//div[contains(@id, \'content\')]"},
{"site" : "*numbersusa.com/content/news*", "start" : "//div[contains(@id, \'zoneContent\')]"},
{"site" : "*usnews.com*", "start" : "//div[contains(@id, \'medium-topper\')]"}
]';

echo $_GET['callback'] . '(' . $jsonData . ');';
?>
